#
# BLACKJACK
#      by Perotin



# Messages used in plugin
number-only: "&cYou must insert a numeric value for your bet!"
no-permission: "&cYou do not have permissions to do this!"
menu-title: "Blackjack: Betting $number$"
blackjack-dealer: "&8&lDealer"
dealer-lore: "&7&oHit or Stand?"
dealer-cards: "&eDealer cards ==>"
player-cards: "&eYour cards ==>"
unknown-card: "&e???"
incorrect-args: "&cImproper arguments > /blackjack <amount>"
hit-item: "&eHit"
stand-item: "&eStand"
end-game: "&7Your Score: &e$score$ &7Dealer Score: &e$score2$"
earnings: "&eYou $result$ $number$ coins!"
won: "won"
lost: "lost"
tied: "&eYou tied so you get your coins back."